# Generated by Django 2.0.5 on 2018-05-12 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nck_cms_manage', '0003_auto_20180512_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_location_houseNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_location_postalCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
